baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'The Patchwork Press'
theme = 'ananke'

[menu]
	[[menu.main]]
	identifier = ""
	name = "Home"
	url = "/"
	weight = 1

	[[menu.main]]
	identifier = "box"
	name = "Secret"
	url = "/box/"
	weight = 2
