baseURL = 'https://thepatchworkpress.github.io'
languageCode = 'en-us'
title = 'The Patchwork Press'
theme = 'rusty-typewriter'
 
[taxonomies]
tag = 'tags'
topic = 'topics'
series = 'series'

[rusty_typewriter]
 [params.rtwt]
  sidePane = true
  countPageItems = 7 
 [params.rtwt.home]
  showBio = true
  showAuthorImg = false
  sidePaneTags = true
  showFeatured = true
  showRecent = true
  hideRecentWhenFeatured = true
  countRecent = 5
 [params.rtwt.side.home]
  sidePaneSticky = true
  taxonomies = ['topics', 'series', 'tags']
  countTaxonomy = 5
 [params.rtwt.side.list]
  sidePaneSticky = true
 [params.rtwt.side.single]
  sidePaneSticky = true 
  showDetails = true
  showTableOfContents = true
  showAttachments = true
  showRelated = true
  countRelated = 5

[params.author]
name = 'Ambrose M Johnston'

[[menu.main]]
identifier = "nonfic"
name = "Essays"
url = "/nonfic/"
weight = 2

[[menu.main]]
identifier = "stories"
name = "Stories"
url = "/stories/"
weight = 3

[[menu.main]]
identifier = "scrapbook"
name = "Scrapbook"
url = "/scrapbook/"
weight = 4

[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 5

[outputFormats]
 [outputFormats.SearchIndex]
  mediaType = "application/json"
  baseName = "searchindex"
  isPlainText = true
  notAlternative = true

[mediaTypes]
 [mediaTypes."application/json"]
  suffixes = ["json"]

[outputs]
 home = ["HTML","RSS", "SearchIndex"]
# ===================================

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true