baseURL = 'https://thepatchworkpress.github.io'
languageCode = 'en-us'
title = 'The Patchwork Press'
theme = 'papermod'

[menu]
	[[menu.main]]
	identifier = ""
	name = "Home"
	url = "/"
	weight = 1
	
	[[menu.main]]
	identifier = "blog"
	name = "Writing"
	url = "/blog/"
	weight = 2

	[[menu.main]]
	identifier = "box"
	name = "Sewing"
	url = "/sewing/"
	weight = 3

	#[[menu.main]]
	#identifier = "first-post"
	#name = "Woaw"
	#url = "/first-post/"
	#weight = 3
