baseURL = 'https://thepatchworkpress.github.io'
languageCode = 'en-us'
title = 'The Patchwork Press'
theme = 'rusty-typewriter'

[outputs]
 home = ["HTML","RSS"] #, "SearchIndex"]
 
[rusty_typewriter]
 [params.rtwt]
  sidePane = true
  countPageItems = 7 
 [params.rtwt.home]
  showBio = true
  showAuthorImg = true
  sidePaneTags = true
  showFeatured = true
  showRecent = true
  hideRecentWhenFeatured = true
  countRecent = 5
 [params.rtwt.side.home]
  sidePaneSticky = false 
  taxonomies = ['tags']
  countTaxonomy = 5
 [params.rtwt.side.list]
  sidePaneSticky = false
 [params.rtwt.side.single]
  sidePaneSticky = true 
  showDetails = true
  showTableOfContents = true
  showAttachments = true
  showRelated = true
  countRelated = 5

[[menu.main]]
identifier = "nonfic"
name = "Essays"
url = "/nonfic/"
weight = 2

[[menu.main]]
identifier = "stories"
name = "Stories"
url = "/stories/"
weight = 3

[[menu.main]]
identifier = "scrapbook"
name = "Scrapbook"
url = "/scrapbook/"
weight = 4

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 5