baseURL = 'https://thepatchworkpress.github.io'
languageCode = 'en-us'
title = 'The Patchwork Press'
theme = 'papermod'

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[[menu.main]]
identifier = ""
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "nonfic"
name = "Essays"
url = "/nonfic/"
weight = 2

[[menu.main]]
identifier = "stories"
name = "Stories"
url = "/stories/"
weight = 3

[[menu.main]]
identifier = "scrapbook"
name = "Scrapbook"
url = "/scrapbook/"
weight = 4

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 5