baseURL = 'https://thepatchworkpress.github.io'
languageCode = 'en-us'
title = 'The Patchwork Press'
theme = 'rusty-typewriter'
 
[params.rtwt.side.home]
taxonomies = ['tags','series']
countTaxonomy = 4

[taxonomies]
tag = 'tags'
topic = 'topics'
series = 'series'

[params.author]
name = 'Ambrose M Johnston'

[[menu.main]]
identifier = "nonfic"
name = "Essays"
url = "/nonfic/"
weight = 2

[[menu.main]]
identifier = "stories"
name = "Stories"
url = "/stories/"
weight = 3

[[menu.main]]
identifier = "scrapbook"
name = "Scrapbook"
url = "/scrapbook/"
weight = 4

[outputFormats]
 [outputFormats.SearchIndex]
  mediaType = "application/json"
  baseName = "searchindex"
  isPlainText = true
  notAlternative = true

[mediaTypes]
 [mediaTypes."application/json"]
  suffixes = ["json"]

[outputs]
 home = ["HTML","RSS", "SearchIndex"]
# ===================================